In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd
import random
from glob import glob
from PIL import Image

In [81]:
def get_images(data_dir,label_dir):
    img_width=random.randint(170,241)
    img_height=img_width
    numpy_image = []
    numpy_label = []

    with tf.name_scope('input'):
        label_list=label_dir
        image_list=data_dir

        temp = np.array([image_list, label_list])
        temp = temp.transpose()
        np.random.shuffle(temp)

        image = tf.cast(image_list, tf.string)
        label = tf.cast(label_list, tf.int32)
        
        input_queue = tf.data.Dataset.from_tensor_slices((image,label))

        for ele in list(iter(input_queue)):
            next_item = ele
            # will show a pair <img tensor, label tensor>
            print(next_item)

            label = next_item[1]
            label = tf.cast(label, tf.int32)

            image_contents = tf.io.read_file(next_item[0])
            image = tf.image.decode_jpeg(image_contents, channels=3)              

            image = tf.cast(image, tf.float32)

            image = tf.image.resize_with_crop_or_pad(image, img_width,  img_height)
            image = tf.image.resize(image, [80, 80],method=tf.image.ResizeMethod.BILINEAR) 

            image = tf.cast(image, tf.float32)
            
            np.savez_compressed('train1_data.npz', label=image)
            numpy_image.append(image)
            numpy_label.append(label)

        return numpy_image,numpy_label

In [82]:
images = glob("Class*_*.jpg")
label = [3,4]
image,label=get_images(images,label)

(<tf.Tensor: shape=(), dtype=string, numpy=b'Class3_4.jpg'>, <tf.Tensor: shape=(), dtype=int32, numpy=3>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Class4_0.jpg'>, <tf.Tensor: shape=(), dtype=int32, numpy=4>)


In [83]:
data1 = np.load('train1_data.npz', 'r')

In [ ]:
tensor.eval()